PROG                ->      ID_DIV [ENV_DIV | DATA_DIV]
ID_DIV              ->      ("ID" | "IDENTIFICATION") "DIVISION" "." ID_DIV_CONTENT
ID_DIV_CONTENT      ->      "PROGRAM-ID" "." USER_SYMBOL "."
ENV_DIV             ->      "ENVIRONMENT" "DIVISION" "."
DATA_DIV            ->      "DATA" "DIVISION" "."


USER_SYMBOL         ->      @KIND=SYMBOL



S -> A [B] [C]

S -> A B 
S -> A C
S -> A B C
S -> A $

A -> a cd D
A -> b cd D 

D -> ed E d 
B -> fcd
C -> gcd 

E -> m
