cobol-source-program	=	( "IDENTIFICATION" | "ID" ) "DIVISION" "." program-id-cobol-source-program
[ identification-division-content ]
[ "ENVIRONMENT" "DIVISION" "." environment-division-content ]
[ "DATA" "DIVISION" "." data-division-content ]
[ procedure-division ]
[ { nested-cobol-source-program }* "END" "PROGRAM" program-name "." ]

Diagrams  Uses  Top  Help


program-id-cobol-source-program	=	"PROGRAM-ID" [ "." ] program-name
[ [ "IS" ] "INITIAL" [ "PROGRAM" ] ] [ "." ]

Diagrams  Uses  Top  Help


nested-cobol-source-program	=	( "IDENTIFICATION" | "ID" ) "DIVISION" "." program-id-nested-cobol-source-program
[ identification-division-content ]
[ "ENVIRONMENT" "DIVISION" "." environment-division-content ]
[ "DATA" "DIVISION" "." data-division-content ]
[ procedure-division ]
{ nested-cobol-source-program }* "END" "PROGRAM" program-name "."

Diagrams  Uses  Top  Help


program-id-nested-cobol-source-program	=	"PROGRAM-ID" [ "." ] program-name
[ [ "IS" ] ( "COMMON" [ "INITIAL" ] | "INITIAL" [ "COMMON" ] ) [ "PROGRAM" ] ] [ "." ]

Diagrams  Uses  Top  Help


identification-division-content	=	( [ "AUTHOR" [ "." ] { comment-entry }* ]
|| [ "INSTALLATION" [ "." ] { comment-entry }* ]
|| [ "DATE-WRITTEN" [ "." ] { comment-entry }* ]
|| [ "DATE-COMPILED" [ "." ] { comment-entry }* ]
|| [ "SECURITY" [ "." ] { comment-entry }* ] )